exports.run = async (bot, msg, args) => {
    if (args.length < 0) return msg.reply('Huh?');
  
    const responses = [
        
        'Ketika kekuatan cinta melebihi cinta terhadap kekuasaan dunia, maka di sana tercipta kedamaian',
        'Jika engkau bingung menentukan pilihan di antara dua cintamu, maka pilihlah yang ke dua. Karena bila engkau memiliki cinta sejati untuk yang pertama, engkau tak mungkin jatuh cinta lagi untuk kedua kalinya',
        'Mereka tahu dan sering berkata ada jutaan ikan di samudra. Tapi mereka tidak mengerti, bahwa engkaulah ‘Ikan Nemo’ yang aku cari',
        'Jangan pernah mengacuhkan seseorang yang mencintaimu, yang peduli padamu, dan yang selalu merindukanmu. Karena suatu hari engkau mungkin terjaga dan menyadari, engkau telah kehilangan bulan di saat sibuk menghitung bintang-bintang',
        'Jangan mencari cinta, biarkan cinta menemukanmu. Itulah mengapa disebut ‘Jatuh Cinta’, karena engkau tak mendorong dirimu terjatuh, tetapi terjatuh begitu saja dalam pesona cinta',
        'Ketika engkau mengetahui alasan mengapa engkau menyukai seseorang, maka itu tak bedanya dengan prinsip bisnis. Namun, jika engkau tak tahu alasannya dan tak memiliki penjelasan, maka itulah CINTA',
        'Hanya ada satu kebahagiaan dalam hidup: Mencintai dan Dicintai. Di mana ada cinta, di sana ada kehidupan',
        'Cinta dilihat bukan dengan mata, tetapi dengan hati. Itulah mengapa peri Cupid digambarkan sosok yang buta',
        'Cinta membutuhkan seseorang. Cinta akan memadukan kelebihan dan kekurangan seseorang. Karena cinta diciptakan untuk saling melengkapi',
        'Hidup tanpa cinta akan membuat dunia tanpa makna. Namun cinta dengan cara yang salah akan membuat dunia berubah sengsara. Demikianlah dualisme cinta',
        'Seorang teman sejati adalah orang yang setia berjalan bersama di saat dunia meninggalkanmu',
        'Seorang sahabat adalah ia yang memberi anda kebebasan total untuk menjadi diri sendiri',
        'Persahabatan dan cinta adalah terapi terbaik untuk proses penyembuhan',
        'Teman sejati adalah dia yang mau berada di dekat anda ketika sebenarnya dia lebih suka berada di tempat lain',
        'Cinta diibaratkan seperti kuncup bunga indah. Sementara persahabatan adalah pohon tempat berlindung',
        'Setangkai bunga mawar bisa menjadi tamanku, dan seorang sahabat bisa menjadi duniaku',
        'Seorang sahabat tidak akan menyembunyikan kesalahan untuk menghindari perselisihan, justru karena kasihnya ia memberanikan diri menegur apa adanya',
        'Sahabat sejati adalah orang yang paling terakhir datang saat kita dalam kegembiraan tetapi selalu pertama datang saat kita sedang kesusahan',
        'Teman yang baik adalah mereka yang menghargai segala kisah kesuksesanmu. Namun sahabat sejati adalah mereka yang menjadi bagian dari kisahmu itu',
        'Menjadi seorang sahabat adalah pekerjaan mudah. Tapi, menjalin persahabatan sejati ibarat pohon langka yang lama berbuah',
        'Optimisme adalah keyakinan yang membawa pada keberhasilan. Tak ada yang bisa dilakukan tanpa harapan dan keyakinan',
        'Meningkatkan pada dasarnya merubah. Menjadi sempurna adalah perubahan yang dilakukan berulang-ulang',
        'Masa lalu memang tak dapat diubah. Tapi masa depan tergantung pada anda',
        'Jangan berusaha menjadi manusia yang sukses, tetapi jadilah manusia yang mempunyai nilai',
        'Sukses adalah kemampuan untuk beralih dari satu kegagalan ke kegagalan lain tanpa sedikitpun kehilangan semangat dan antusiasme',
        'Pertama, mereka mengabaikan anda. Kemudian, mereka menertawakan anda. Berikutnya, mereka melawan anda. Lalu, anda menang',
        'Kesalahan adalah guru terbaik manusia ketika ia cukup jujur untuk mengakuinya dan bersedia untuk belajar dari mereka',
        'Persiapan yang terbaik untuk hari esok adalah melakukan pekerjaan hari ini dengan sangat baik',
        'Fokus pada masalahmu, engkau tak akan mendapat solusi terbaik. Fokus pada Tuhan, Dia akan memberimu jalan keluar',
        'Belajarlah menyalakan lilin di saat-saat tergelap dari kehidupan orang lain. Jadilah cahaya yang membantu orang lain untuk melihat. Itulah arti kehidupan yang mendalam',
        'Dibalik setiap rasa duka dan sedih, tersembunyi kebahagiaan. Serahkan segala urusan kepada Tuhan. Biarkan waktu dan kehidupan berjalan',
        'Tak ada musuh yang perlu engkau takuti dalam kehidupan ini, selain kesombonganmu sendiri',
        'Bersyukur atas keberhasilan itu sudah biasa, namun bersyukur atas kegagalan itulah hal yang luar biasa',
        'Hidup ini terlalu singkat jika hanya digunakan untuk memendam dendam yang berkepanjangan',
        'Kehidupanmu adalah buah dari tindakan yang engkau lakukan. Tidak ada yang bisa disalahkan selain dirimu sendiri',
        'Pelajaran terbesar yang dapat aku pelajari dalam hidup ini adalah bahwa aku masih harus banyak belajar',
        'Jika kau berlutut dihadapan Tuhan maka kau akan berdiri dihadapan manusia',
        'Terkadang manusia menunggu datangnya kekuatan untuk bertindak, padahal dengan bertindak justru dapat menghadirkan kekuatan',
        'Kedewasaan adalah saat kita mulai membicarakan hal-hal besar dengan memahami hal yang terlihat sepele',
        'Menunggu itu menyakitkan. Melupakan juga menyiksa hati. Namun, tak mengetahui harus melakukan yang mana adalah penyiksaan yang terburuk',
        'Aku akan selalu merasa bahagia dengan melihatmu bahagia, walaupun yang membahagiakanmu bukan aku',
        'Rasa cinta yang memberikan tangis,air mata itulah yang mengajarkan kita tentang kebahagian di masa depan',
        'Mencoba melupakan orang yang anda cintai sama saja dengan mencoba mengingat orang yang tidak pernah anda jumpai',
        'Sebuah jiwa sedih bisa membunuh lebih cepat dari sebuah kuman',
        'Memang menyakitkan ketika membiarkanmu pergi. Tetapi akan lebih menyakitkan jika terus menahanmu',
        'Hatiku menjadi pembohong manakala merelakanmu bersatu dengan si dia',
        'Lebih baik bersedih bersama orang yang tepat dari pada bahagia tetapi dengan orang yang salah',
        'Di tengah kehampaan ini, hanya bersamamu Tuhan yang akan selalu membuatku merasa hidup',
        'Ambil pelajaran dari masa lalu, tinggalkan sisanya. Jangan biarkan belenggu kesedihan menutup jalanmu menuju masa depan',
        'Jika aku harus memetik bunga setiap teringat dirimu, maka pastinya aku akan berjalan menyusuri kebun bunga selamanya. Itu karena tak ada sedetik waktu pun dalam hidupku tanpa teringat dirimu',
        'Ketika kita mencintai, kita akan selalu berusaha untuk menjadi sosok yang lebih baik. Ketika kita berusaha untuk menjadi lebih baik, maka segala sesuatu di sekitar kita akan menjadi lebih baik juga. Demikianlah kekuatan cinta',
        'Hidup adalah 10% apa yang terjadi pada Anda dan 90% bagaimana Anda bereaksi terhadap kondisi itu',
        'Hiduplah seperti pohon kayu yang lebat buahnya, hidup di tepi jalan dan dilempari dengan batu, tapi membalasnya dengan buah',
        'Sekali anda mengerjakan sesuatu, jangan takut gagal dan jangan tinggalkan itu. Orang-orang yang bekerja dengan ketulusan hati adalah mereka yang paling bahagia',
        'Kebanggaan kita yang terbesar bukan karena tidak pernah gagal, tetapi bangkit kembali setiap kali terjatuh',
        'Ada tiga hal yang harus dimiliki dalam hidup, Perubahan, Pilihan, dan Prinsip',
        'Perubahan dalam hidup memang tidak menjamin keberhasilan, namun tidak ada keberhasilan tanpa perubahan',
        'Kalau hidup hanya sekedar hidup, kera di rimba juga hidup. Kalau hidup hanya sekedar bekerja kerbau di sawah pun bekerja. Karena hidup bukan sekedar hidup jika hidupmu tidak bermanfaat bagi kehidupan orang lain',
        'Kedewasaan adalah saat kita mulai membicarakan hal-hal besar dengan memahami hal yang terlihat sepele',
        'Penyesalan akan selalu datang di akhir dan bukan di awal, karena ia tau bahwa ada segelintir orang yang membutuhkan penyesalan',
        'Sakit hati itu berat, tapi kamu akan menemukan banyak hal untuk disyukuri setiap harinya',
        'Ku dengar, kamu telah menjadi sebuah buku. yang menceritakan aku, dengan segala kemalanganku',
        'Harusnya Tuhan menciptakan waktu berjalan dua arah supaya aku bisa kembali ke masa lalu untuk menghapus semua penyesalanku',
        'Sakit karena menangis. Lelah karena mencoba. Namun aku tetap tersenyum. Meski hatiku mati dan membeku',
        'Jika menyakitiku adalah jalan yang memang akan membuatmu bahagia, maka lakukanlah',
        'Cinta adalah jalinan persahabatan yang telah terbakar. Hariku takkan sempurna tanpa mengucapkan I Love You”',
        'Cinta terbaik adalah cinta yang membangkitkan jiwa, yang membuat kita bisa meraih lebih, yang membakar semangat dalam hati, tetapi mendamaikan pikiran',
        'Ketika seseorang mencintaimu, dia tak mesti mengatakannya. Engkau dapat merasakan melalui caranya memperlakukanmu',
        'Suatu hari, engku akan berjumpa dengan seseorang yang tak peduli dengan masa lalumu, karena ia ingin bersamamu di dalam masa depanmu',
        'Indonesia adalah negeri budak. Budak di antara bangsa dan budak bagi bangsa-bangsa lain',
        'Benar di mata manusia belum tentu benar di mata Allah, begitu juga buruk di mata manusia belum tentu buruk di mata Allah',
        'Hidup ini hanya sekali dan peluang itu juga sekali munculnya, keduanya tidak datang dua kali',
        'Entah mengapa hari-hari ini akan cepat berlalu, dan senjapun mulai memberi kabar bahwa dia akan berlaku',
        'Hidup tak semudah membalikkan telapak tangan, tetapi dengan telapak tangan kita dapat merubah hidup kita jauh lebih baik lagi',
        'Penampilan memang tidak meyakinkan bahwa dia itu pintar atau bodoh',
        'Rencanakan sendiri target sukses anda arungi ala ide perwujudannya, rasakan indahnya memperoleh dampak tetes keringat kreativitas anda, bukan atas intruksi siapapun',
        'Jangan remehkan modal yang kecil, takukanlah kecilnya modal keberanian',
        'Semangat mengubah hidup dengan doa, kesabaran, keikhlasan, ikhtiar akan menjadi ibadah yang sempurna di hadapan Allah',
        'Bisnis kecil bila disyukuri akan menjadi bisnis besar',
        'Orang sukses akan mengambil kesulitan sebagai peluang, orang gagal memandang kesulitan sebagai penghambat dirinya',
        'Jadilah pribadi yang menantang masa depan, bukan pengecut yang aman di zona nyaman',
        'Pembisnis itu harus menelan pengalaman selama berusaha, dengan pengalaman itu yang membuat ia sukses',
        'Pengusaha besar memainkan peran lebih besar dalam perekonomian dunia, pengusaha kecil merampas banyak potensi untuk dari bisnis besar',
        'Hidup tak selamanya tentang pacar',
        'Dan sepahit-pahitnya kehidupan mulai melebur saat ku terbiasa dengan keberadaanmu yang manis',
        'Pengusaha itu bukan orang yang pintar tetapi mereka pintar mencari orang pintar',
        'Belajarlah rendah hati, rendahkan hatimu serendah-rendahnya hingga tidak ada seorangpun yang bisa merendahkanmu',
        'Ketika anda mempekerjakan orang yang lebih pintar daripada anda, maka anda telah membuktikan bahwa anda lebih pintar dari mereka',
        'Jika kamu gagal mendapatkan sesuatu hanya satu hal yang harus kamu lakukan, yaitu coba lagi',
        'Dunia tak lagi sama tak selamanya memihak kita, disaat kita mau berusaha disitulah kebahagiaan akan indah pada waktunya',
        'Memaafkan belum tentu membuat kita lebih baik atau bahkan merasa lebih baik tetapi yang jelas membuka jalan kebaikan',
        'Jangan menyerah atas impianmu, impian memberi tujuan hidup. Ingatlah sukses bukan kunci kebahagiaan, kebahagiaan adalah kunci kesuksesan',
        'Jangan menyepelekan perkataan orang tua, karena perkataan tersebut akan menjadi kebahagiaan kita, percayalah',
        'Setiap orang ada bakatnya masing-masing, kenali dan kembangkanlah bakat itu, dengan begitu kesuksesan akan menunggu kita di hari esok',
        'Berusahalah terus, meski gagal terus menghantui lagi dan lagi, tapi selalu ada masa kita sukses lagi dan lagi',
        'Jangan pernah merasa tersusah di dunia, karena masih ada yang lebih susah, bersyukurlah',
        'Kekayaan adalah produk dari kapasitas pemikiran manusia',
        'Mudah untuk menemukan kebenaran sulit untuk menghadapinya dan lebih sulit untuk mengikutinya',
        'Mimpiku sangat sederhana yaitu mencintaimu dan memiliki ikatan yang halal',
        'Orang dengan ide baru adalah orang yang aneh sampai ide itu berhasil',
        'Perselisihan tidak dapat diabaikan atau disembunyikan, dia harus diselesaikan',
        'Sombong adalah menjatuhkan seseorang dan hanya berpihak kepada orang yang dianggap memiliki banyak uang',
        'Adalah suatu kemungkinan menggapai apa yang tidak mungkin bagi yang lain',
        'Untuk mereka yang selalu menerbangkan namaku dalam doa, yang mengucap lirih bait-bait pinda pada yang maha kuasa, perihal suksesku, keberhasilanku. Kuatkan aku untuk mereka, agar tak mudah lelah pun menyerah',
        'Menjadi orang yang benar memang tidak merepotkan, yang membuat repot itu orang yang merasa selalu benar',
        'Jika bintang jatuhnya entah kemana, aku hanya ingin jatuhnya tepat dihadapanku',
        'Kita berhak menilai seseorang tapi kita tidak berhak menghakimi mereka, Allah lebih mengetahui apa yang tidak kita ketahui',
        'Namun kau tidak akan pernah tahu bagaimana rasanya ingin memiliki sesuatu yang bahkan seujung kukupun tak berhak memilikinya',
        'Jika kau tidak mampu melakukan sesuatu yang besar, jadilah apatis, karena itu lebih baik daripada skeptic',
        'Bahagia itu sederhana, ketikamenerima nikmat-Nya yang tiada taranya berkata Alhamdulillah',
        'Simbol dari kekayaan itu mendapatkan, sedangkan symbol dari kebahagiaan itu memberikan',
        'Jadilah apa yang benar di mata Allah, buka sekedar yang dapat dibenarkan oleh pandangan manusia',
        'Tidak semua orang yang baik untukmu adalah baik untuk orang lain',
        'Dalam hidup tak penting siapa yang menyukai atau membencimu, yang terpenting Allah selalu mencintimu tanpa syarat',
        'Apa yang Allah berikan untuk kita pasti yang terbaik, meskipun yang terbaik itu bukan yang terindah',
        'Pertolongan Allah mungkin tidak datang terlalu cepat, tidak juga datang terlalu lambat. Tetapi pertolongan Allah akan selalu datang disaat yang tepat',
        'Hikmah Allah memberikan mulut di depan, agar kita tidak membicarakan orang lain di belakang',
        'Ada 2 kegagalan yang sering terjadi, yaitu yang selalu berfikir tapi tidak pernah bertindak dan orang yang bertindak tapi tidak pernah berfikir',
        'Mencintai itu butuh tenaga, jangan kau buang tenagamu untuk berlari dan menyerah',
        'Semoga kita tidak termasuk orang yang kehilangan kesempatan untuk meminta maaf kepada orang-orang yang kita pernah berbuat kesalahan kepadanya',
        'Kau tau? Bahagia itu sangat sederhana, mensyukuri, mencintai dan menjaga apa yang kita miliki',
        'Cobalah untuk selalu menghargai apapun itu, karena terkadang sesuatu akan jauh terasa lebih berharga saat kita kehilangannya',
        'Semoga kita termasuk orang yang berhati-hati dalam menjaga hati dan tidak memberikan kepada seseorang yang tak bisa menghargai. Karena ketika diberi, dia takkan sepenuhnya kembali',
        'Bagi siapapun yang pernah kehilangan semangat, kegagalan hanyalah sebuah hal yang sifatnya sementara',
        'Hidup adalah sebuah pilihan, sesuatu yang kita pilih akan menentukan kebahagiaan kita di masa depan. Begitupun saat keita memilih pasangan',
        'Bersyukur dapat menyadarkan kita akan pentingnya arti menikmati kehidupan, seburuk apapun keadaannya',
        'Ada 3 hal yang tidak pernah terlambat untuk kita lakukan, yaitu mencintai, memaafkan dan memperbaiki diri',
        'Bukan bahagia yang menjadikan kita bersyukur, tetapi dengan bersyukurlah yang akan menjadikan hidup kita bahagia',
        'Syukur adalah kebahagiaan instan, jika kita bersyukur detik ini maka kita akan bahagia detik ini pula',
        'Mungkin dari sebuah kehilangan kita bisa tahu bahwa cinta itu benar-benar ada, namu terhalang ego yang menutup rasa tulus di hati kita',
        'Terima kasih telah tidak membalas chatku dengan cara tidak membukanya. Karena aku bisa berfikir positif kamu tidak sengaja melewatkannya, bukan mengabaikannya',
        'Jika semua pemberian kita syukuri dengan sungguh-sungguh, maka tak perlu kita tangisi kehilangan, karena dia akan menggantinya seratus kali',
        'Menangislah karena itu pertanda bahwa hatimu belum berubah menjadi batu',
        'Dalam permohonan atau permintaan, hanya ada dua jawaban, berbalas maka bersyukurlah. Jika sebaliknya maka bersabarlah, karena keduanya mengandung pelajaran',
        'Menjadi orang baik tidak haru dianggap baik oleh semua orang, melaikan cukup dengan sebanyak mungkin orang menilai kita baik',
        'Beragam pandangan orang-orang terhadap kita, ada yang melihat kita orang buruk dan jelek, ada yang melihat kita orang baik. Bahkan ada yang tidak melihat keberadaan kita sama sekali',
        'Jangan rusak hidupmu hanya dengan iri atas nikmat yang Allah berikan pada orang lain',
        'Kadang hati memang senantiasa sadar akan setiap kesalahan, namu kesadaran seringkali tidak bisa mengendalikan perbuatan',
        'Tidak ada seorangpun yang siap dengan perpisahan, namu setiap ada pertemuan pasti akan ada perpisahan',
        'Hidup tidak mengenalkan kita kepada orang-orang yang kita inginkan, tetapi mengenalkan kita kepada orang-orang yang kita butuhkan. Yaitu orang-orang yang membuat hidup kita ini jauh lebih bermakna',
        'Hati yang peka akan bersyukur, selalu mudah bahagia atas hal-hal baik sekecil apapun',
        'Sehat itu mahal daripada kaya, sebab apabila sudah sakit-sakitan kekayaan bisa hilang',
        'Seperti sudah pada rumusnya, semakin kita bekerja keras dan berdoa, semakin dunia yang tadinya melawan akan melunak',
        'Ada perjuangan yang belum tertuntaskan, doa yang belum terkabulkan, dan harapan yang belum terwujudkan. Mungkin sabar adalah sebuah jawaban',
        'Pada akhirnya, pasti aka nada seseorang yang menguatkan kita, entah dengan cara menyakiti atai dengan menyemangati',
        'Kehidupan punya cara tersendiri untuk menyeleksi setiap kehendak kita, kita tidak bisa memilih apa yang kita kehendaki, yang terbaik adalah apa yang kita miliki dan syukuri',
        'Semoga kita bukan termasuk orang yang mengejar dan pergi untuk menjauh dan tidak sadar meninggalkan yang mengejar untuk mendekat',
        'Indahnya kebersamaan jika kita mengajak bukan sibuk mengejek dan bukan saling pukul tapi merangkul',
        'Sabar itu tidak hanya diam, tetapi tidak membalas perbuatan orang lain, tetapi mencoba berusaha bagaimana seseorang itu tidak melakukan kesalahan itu lagi',
        'Tawakal itu suasana hati ketika sudah melakukan segala sesuatu secara maksimal dengan mengharapkan pertolongan Allah. Ketika kita sudah menyerahkan semua kepada Allah ketenangan hati itupun akan datang',
        'Kadang memang dunia ini memperlihatkan kesulitan, namun semua kesulitan sudah sepaket dengan solusinya, jika belum melihatnya bersilaturahmilah',
        'Dengan adanya perpisahan kita menjadi tau dari sebuah arti perjuangan yang sesungguhnya',
        'Ketika indera perasa menjadi penambah rasa dalam berbicara kejujuran dan kebohongan sulit untuk dibedakan',
        'Berapapun rezeki dari sang ilahi robbi, patut disyukuri, semangat tiada henti',
        'Uang hanya sekedar angka, angka tiada batas, kebahagiaan tidak dapat diukur dengan angkan dan bisa dirasa atau diberi tanpa batas terhingga',
        'Tidak ada target besar, yang ada adalah impian kita yang terlalu kecil',
        'Muda tidak terulang lagi, pikul beban semaksimal mungkin, agar di masa tua tidak menyesal',
        'Bukan karena siapa dirimu menyayangi tapi karena apa yang terjadi padaku saat bersamamu',
        'Ketika Allah telah mentakdirkan jalan penantian untuk ditapaki, maka kesabaran dan doa adalah cara terbaik untuk menitinya',
        'Keberhasilan yang paling sweet adalah ketika kita mencapai sesuatu yang menurut orang lain tidak mungkin',
        'Hidup jangan dipersulit dan dipermudah, lakukanlah dari hal-hal yang sederhana',
        'Menjadi orang yang benar tidaklah sulit, yang sulit adalah berhenti menjadi orang yang sok benar',
        'Berbaik sangkalah kepada Allah dalam situasi apapun, sebab tuhan tak memberi cobaan melebihi batas kemampuan',
        'Berbohong justru hanya menyusahkan kita, karena dengan berbohong kamu harus mengingat setiap kebohongan yang kamu ucapkan selamanya',
        'Jangan lupa syukuri keadaanmu saat ini karena mungkin keadaan yang kamu keluhkan menjadi keadaan yang diidamkan orang lain',
        'Aku bukan orang yang baik tapi aku akab berusaha untuk hijrah menjadi lebih baik',
        'Kita tak perlu baik tuk semua orang, tapi setidaknya kita bisa menghargai semua kebaikan orang pada kita',
        'Detail terkecil yang berhasil akan menuntuk pada kesuksesan yang besar',
        'Menjadi bermanfaat itu baik, berbuat jujut itu mudah, kebohongan dan keburukanlah yang menipu',
        'Bersatu memang sulit, karena menyatukan visi tidaklah mudah, untuk itulah dibutuhkan pemimpin',
        'Keterbatasan hanya membuat kita terjebak dalam keinginan sebatas mimpi',
        'Mencapai sukses bersama itu lebih baik daripada sekedar mimpi terencana bersama tanpa aksi nyata',
        'Kamu tidak akan menemukan semangatmu sebelum kamu menemukan tujuan hidupmu',
        'Mari kita belajar dari kopi, walalu pahit terkadang rasanya pahit tapi itu yang membuat mata kita lebih terbuka',
        'Skill dapat diraih dari apa saja, baik penalaran dan pengalaman, namu guru yang baik adalah pengalaman, dan lebih baik lagi jika itu pengalaman orang lain',
        'Keren itu saat apa yang kita miliki bisa menjadikan kita memiliki apa yang tidak dimiliki',
        'Sucikan diri, karena sesungguhnya yang suci datang pada jiwa yang suci pula',
        'Keterbatasan seorang guru mengajarkan tentang arti pengabdia dan kreatifitas pada anak bangsa',
        'Ingatkan aku jika aku salah, agar aku bisa memperbaikinya. Jangan malah menghinaku dari belakang sebab hal itu akan mengubahku',
        'Sendiriku tak berarti sepi diamku tak berarti sunyi mungkin kalian saja yang tak mengerti, inilah caraku memantaskan diri',
        'Kita merancang, kita merencanakan tapi ketetapan Allah adalah yang terindah dan yang terbaik. Kita merancang dengan cita, namu Allah merancang dengan cinta, selalu berprasangka baik pada Allah',
        'Mau adalah kata sederhana dari mampu',
        'Pekerjaan sulitpun jika dikerjakan dengan bahagia pasti akan menyenangkan',
        'Cobalah untuk sukses, jauhi potensi kegagalan. Tapi kadang memang perlu mencicipi sebentar, agar kita tau kebahagiaan sesungguhnya. Sekaligus cara berbagi dan bermanfaat ke sesama',
        'Hati-hati, kadang saat kita kesal, orang pertama yang menjadi luapan semodi adalah orang yang kita sayangi',
        'Semangat menjari rezeki full barokah, makin banyak makin berkah, dapat sedikit tetap Alhamdulillah',
        'Semangat itu saat dirimu menghadirkannya',
        'Kita dan sistem sosia adalah kesatua demi tujuan peradaban',
        'Berperikemanusiaan itu mudah, cukup memanusiakan manusia lainnya',
        'Mulut lancang berbicara, lidah tajam bagai belati, meski tiada niat menyakiti. Penyesalan hadir meski air mata tak sanggup mengganti',
        'Miliki visi tuk mengukir misi, upayakan sekuat tenaga agar asa jadi nyata',
        'Ciptakan peluang kemenagan tak perlu sibuk iri dengan kesuksesan dan menutup peluang orang lain',
        'Tidak ada yang salah dari melakukan yang terbaik',
        'Cobalah gapai suksesmu sebagai dirimu sendiri, tak perlu menjadi orang lain',
        'Sudahlah, penyesalah memang selalu datang di belakang, jadikan ia bagian dari kenangan dan pengalaman. Karena ini terlalu berharga di idi dengan masa lalu'

    ];
  
    msg.channel.send('```📧' + (responses[Math.floor(Math.random() * responses.length)]) + '📜```');
  };
  
  exports.conf = {
    aliases: ['ask'],
    guildOnly: true,
  };
  
  exports.help = {
    name: 'quotes',
    aliases: ['quote', 'quo'],
  };
